# Flags are currently ignored
mounts = [
	{src = "proc", dst = "/proc", type = "proc", flags = ""},
	{src = "tmp", dst = "/tmp", type = "tmpfs", flags = ""},
	{src = "dev", dst = "/dev", type = "devtmpfs", flags = ""},
	{src = "sys", dst = "/sys", type = "sysfs", flags = ""},
]

# Login information
[login]
shell = "schelp"
home = "/home"
user = "root"
cwd = "/"
